### ISSUE TITLE
gdb file builds fine, but clamav not using it?

### ISSUE THREAD

**Issue by jeffrysleddens** [Cisco-Talos/clamav-safebrowsing#3] opened 2021-03-16 17:47 UTC
I have clamav-safebrowsing working well. It retrieves the hashes from Google, stores them in the database and it builds a nice size gdb file.

ClamAV does read the gdb file, and shows the signatures added:
LibClamAV debug: hashtab: Growing hashset, used: 943718, capacity: 1048576
LibClamAV debug: hashtab: Freeing hashset, elements: 943718, capacity: 1048576
LibClamAV debug: safebrowsing.gdb loaded

but when I scan a text file with the following URL (http://malware.testing.google.test/testing/malware/) it says everything is ok and does not detect that the URL is bad.

**Comment by val-ms** [comment] 2021-03-20 20:37
ClamAV isn't able to detect URLs in plain text.  It should detect the `<a href="http://malware.testing.google.test/testing/malware/"> .... </a>` url in an HTML file.

**Comment by jeffrysleddens** [comment] 2021-03-23 11:23
Thank you for your reply.  I did find bug 12053 on ClamAV's bugzilla (https://bugzilla.clamav.net/show_bug.cgi?id=12053) which also explains this.

Unfortunatly though my setup also does not detect the link in an HTML file:

Contents of test.html:

    <html>
        <body>
            <a href="http://malware.testing.google.test/testing/malware/">linkje</a>
        </body>
    </html>

Output of clamscan test.html:

    /tmp/test.html: OK
    
    ----------- SCAN SUMMARY -----------
    Known viruses: 14389111
    Engine version: 0.102.4
    Scanned directories: 0
    Scanned files: 1
    Infected files: 0
    Data scanned: 0.00 MB
    Data read: 0.00 MB (ratio 0.00:1)
    Time: 56.042 sec (0 m 56 s)

**Comment by xpunkt** [comment] 2021-04-08 15:59
i can confirm that i have not seen any safebrowsing detection here, i turned that database off long time ago

**Comment by toushin-taishi** [comment] 2021-05-19 04:00
I did send myself an e-mail using GMAIL with the following URL in the body:

> http://malware.testing.google.test/testing/malware/

and it was detected as:

> Virus scanner output:
>   p004: Heuristics.Safebrowsing.Suspected-phishing_safebrowsing.clamav.net FOUND

Does this result show that ClamAV uses the gdb file?

**Comment by jeffrysleddens** [comment] 2021-05-19 06:07
It does look like it.  I am very curious about how you have set up ClamAV to scan your mail. Could you please describe your setup (which MTA, and scanning middleware (spamassassin, rspamd))?

**Comment by toushin-taishi** [comment] 2021-05-19 09:55
Hi @jeffrysleddens,

In my test, clamav does not have (or support?) safebrowsing detection when scanning HTML nor TXT file.
However, if it's an e-mail file, it does. You can test by sending yourself an e-mail with the URL in the body or saving it as an .EML file and scan it with clamav.

e.g.

> [foo@srv tmp]# clamscan --verbose \[utm9\]\ \ WARNING\:\ QUOTA\ ERROR\ CAUSING\ CLUSTERED\ MESSAGES\ FOR\ info@domain.eml 
> Scanning /tmp/[utm9]  WARNING: QUOTA ERROR CAUSING CLUSTERED MESSAGES FOR info@domain.eml
> LibClamAV info: Suspicious link found!
> LibClamAV info:   Real URL:    https://fabbinpinna.web.app/urb/gx.html?email=info@domain
> LibClamAV info:   Display URL:  												 												Clear clustered message(s) now
> LibClamAV info: Suspicious link found!
> LibClamAV info:   Real URL:    https://fabbinpinna.web.app/urb/gx.html?email=info@domain
> LibClamAV info:   Display URL:  												 												Clear clustered message(s) now
> /tmp/[utm9]  WARNING: QUOTA ERROR CAUSING CLUSTERED MESSAGES FOR info@domain.eml: Heuristics.Safebrowsing.Suspected-malware_safebrowsing.clamav.net FOUND

However, if it's an HTML file:

> [foo@srv tmp]# clamscan --verbose \[utm9\]\ \ WARNING\:\ QUOTA\ ERROR\ CAUSING\ CLUSTERED\ MESSAGES\ FOR\ info@domain.html 
> Scanning /tmp/[utm9]  WARNING: QUOTA ERROR CAUSING CLUSTERED MESSAGES FOR info@domain.html
> /tmp/[utm9]  WARNING: QUOTA ERROR CAUSING CLUSTERED MESSAGES FOR info@domain.html: OK
> 

Also, please check if the heuristic phishing detection is enabled in your clamd configuration as mentioned in freshclam.conf. 
 
For your question, I am using Postfix and Amavisd-new.




HTH

*** EDIT ***
Based on the above information, I made some additional tests. It seems since amavisd has an option to let the virus scanner see the full original message, clamav can detect using the safebrowsing signatures as clamav is scanning the entire email message and not just the decoded parts. Here is the relevant config in amavisd-new:

> @keep_decoded_original_maps = (new_RE(
>   qr'^MAIL$',                # let virus scanner see full original message
> ));
> 

When I disabled this configuration, clamav failed to detect using the safebrowsing signature. 

Hope this helps.

**Comment by val-ms** [comment] 2022-11-04 18:48
I am going to close this issue, since this is not an issue with the clamav-safebrowsing tool.

I can see the appeal of having clamav alert on URL's in HTML, TXT, and other documents.  You're welcome to submit a feature request for URL extracting/scanning in other file types on the main https://github.com/Cisco-Talos/clamav project issue tracker.  It is something that our threat research team is also interested in.  I'm hopeful we'll be able to add that eventually.

**Closed as completed by val-ms** 2022-11-04 18:48 UTC
